apiVersion: v1
kind: Service
metadata:
  name: voce-aluga-backend
  namespace: voce-aluga
  labels:
    app.kubernetes.io/name: voce-aluga-backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: voce-aluga-backend
  ports:
    - name: http
      port: 8080
      targetPort: http
