apiVersion: v1
kind: ResourceQuota
metadata:
  name: voce-aluga-quota
  namespace: voce-aluga
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 3Gi
    limits.cpu: "6"
    limits.memory: 6Gi
    pods: "10"
