apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voce-aluga-frontend
  namespace: voce-aluga
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: voce-aluga-frontend
                port:
                  number: 80
